name: Pro-Rad
favicon: null
layout_spectrum: 0.41081421286799014
typography_spectrum: 0.9778100873809308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8192787691950798
  lightness: 0.7954870401881635
  saturation: 0.8460934122558683
  rhythmicContrast: 0.12408653553575277
purpose: []
